/* Generated by bin2c, do not edit manually */
#ifndef __logo_jpg_h_included
#define __logo_jpg_h_included

/* Contents of file logo.jpg */
extern const long int bin2c_logo_jpg_size;
extern const unsigned char bin2c_logo_jpg[211199];

#endif    /* __logo_jpg_h_included */
